[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "onedata4sci"
authors = [{name = "Tomáš Svoboda", email = "svoboda@ics.muni.cz"}, {name = "Aleš Křenek", email = "ljocha@ics.muni.cz"}]
dynamic = ["version", "description"]
